[package]
name = "mndp"
version = "0.2.0"
authors = ["Christopher Bruton <chris@bruton.tech>"]
edition = "2021"
publish = false

[dependencies]
bytes = "1.8.0"
macaddr = "1.0.1"

[dev-dependencies]
hex = "0.4.3"
strum = { version = "0.26", features = ["derive"] }
